DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS FoodOrder;
DROP TABLE IF EXISTS Store;
DROP TABLE IF EXISTS ItemsInOrder;

CREATE TABLE Users ( 
  login TEXT NOT NULL PRIMARY KEY,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  favoriteItems TEXT,
  phoneNum TEXT NOT NULL
);

CREATE TABLE Items ( 
  itemName TEXT NOT NULL PRIMARY KEY,
  ingredients TEXT NOT NULL,
  typeOfItem TEXT NOT NULL,
  price REAL NOT NULL,
  description TEXT
);

CREATE TABLE Store ( 
  storeID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  isOpen TEXT NOT NULL,
  reviewScore REAL
);

CREATE TABLE FoodOrder ( 
  orderID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  login TEXT NOT NULL, 
  storeID INTEGER NOT NULL, 
  totalPrice REAL NOT NULL,
  orderTimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  orderStatus TEXT,
  FOREIGN KEY(login) REFERENCES Users(login) ON DELETE CASCADE,
  FOREIGN KEY(storeID) REFERENCES Store(storeID) ON DELETE CASCADE
);

CREATE TABLE ItemsInOrder ( 
  orderID INTEGER NOT NULL,
  itemName TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  PRIMARY KEY(orderID, itemName),
  FOREIGN KEY(orderID) REFERENCES FoodOrder(orderID) ON DELETE CASCADE,
  FOREIGN KEY(itemName) REFERENCES Items(itemName) ON DELETE CASCADE
);
